AWSTemplateFormatVersion: "2010-09-09"
Resources:
  NextjsCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: TO_BE_REPLACED
            Id: S3StaticOrigin
            S3OriginConfig:
              OriginAccessIdentity: ""
          - DomainName: TO_BE_REPLACED
            Id: S3PublicOrigin
            OriginPath: /public
            S3OriginConfig:
              OriginAccessIdentity: ""
          - DomainName:
              Fn::Join:
                - ""
                - - Ref: ApiGatewayRestApi
                  - ".execute-api.us-east-1.amazonaws.com"
            Id: ApiGatewayOrigin
            OriginPath: /dev
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
        Enabled: "true"
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          TargetOriginId: ApiGatewayOrigin
          ForwardedValues:
            QueryString: "true"
            Cookies:
              Forward: all
          ViewerProtocolPolicy: allow-all
        CacheBehaviors:
          - AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            TargetOriginId: S3StaticOrigin
            ForwardedValues:
              QueryString: "false"
              Cookies:
                Forward: none
            ViewerProtocolPolicy: allow-all
            MinTTL: "50"
            PathPattern: static/
        PriceClass: PriceClass_All
