next-app-with-locales:
  component: "../../serverless-components/nextjs-component"
  inputs:
    build:
      postBuildCommands: ["node scripts/post-build-test.js"]
    cloudfront:
      defaults:
        forward:
          headers: [Authorization]
          cookies: [NEXT_LOCALE]
      api/*:
        forward:
          headers: [Authorization]
